# -*- coding: utf-8 -*-
"""factorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16AOTV4oLNlRqIP4kR6EX0sdYDm1H7rVQ
"""

n=5
fact=1
for i in range(1,n+1):
  fact = fact*i
  print("Factorial of", n, "=", fact)